//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace project5_voting.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Debate
    {
        public long id { get; set; }
        public string electionArea { get; set; }
        public string firstCandidate { get; set; }
        public string firstCandidateID { get; set; }
        public string firstCandidateList { get; set; }
        public string secondCandidate { get; set; }
        public string secondCandidateID { get; set; }
        public string secondCandidateList { get; set; }
        public string subject { get; set; }
        public string message { get; set; }
        public string zoomLink { get; set; }
        public Nullable<int> status { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public Nullable<System.TimeSpan> time { get; set; }
    }
}
