//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace project5_voting.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ElectionsEntities2 : DbContext
    {
        public ElectionsEntities2()
            : base("name=ElectionsEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Ad> Ads { get; set; }
        public virtual DbSet<Admin> Admins { get; set; }
        public virtual DbSet<Contact> Contacts { get; set; }
        public virtual DbSet<Date> Dates { get; set; }
        public virtual DbSet<Debate> Debates { get; set; }
        public virtual DbSet<localCandidate> localCandidates { get; set; }
        public virtual DbSet<localList> localLists { get; set; }
        public virtual DbSet<partyCandidate> partyCandidates { get; set; }
        public virtual DbSet<partyList> partyLists { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<USER> USERS { get; set; }
        public virtual DbSet<electionArea> electionAreas { get; set; }
    }
}
