//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace project5_voting.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class partyCandidate
    {
        public long id { get; set; }
        public Nullable<long> partyId { get; set; }
        public string email { get; set; }
        public string name { get; set; }
        public string phone { get; set; }
        public string nationalId { get; set; }
        public string gender { get; set; }
        public Nullable<System.DateTime> birthDay { get; set; }
        public string typeOfChair { get; set; }
        public string religion { get; set; }
        public string status { get; set; }
        public string electoralDistrict { get; set; }
    
        public virtual partyList partyList { get; set; }
    }
}
