//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace project5_voting.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class USER
    {
        public long id { get; set; }
        public string NationalID { get; set; }
        public string name { get; set; }
        public string email { get; set; }
        public string password { get; set; }
        public string gender { get; set; }
        public Nullable<System.DateTime> birth_date { get; set; }
        public string religion { get; set; }
        public string governorate { get; set; }
        public string election_area { get; set; }
        public string election_location { get; set; }
        public Nullable<int> localYouth { get; set; }
        public Nullable<int> partyVote { get; set; }
        public Nullable<int> whileLocalVote { get; set; }
        public Nullable<int> whilePartyVote { get; set; }
    }
}
